esphome:
  name: "paj7620"
  comment: "paj7620 Smart IR Gesture Sensor tester"

esp8266:
  board: nodemcuv2

logger:

api:
  password: !secret api_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password




external_components:
  - source: components

text_sensor:
  - platform: paj7620
    name: "My gesture sensor"
