esphome:
  name: "paj7620"
  comment: "paj7620 Smart IR Gesture Sensor tester"
    
esp8266:
  board: nodemcuv2

external_components:
  - source: github://apaex/PAJ7620-ESPHome

sensor:
  - platform: paj7620
